<a href="https://colab.research.google.com/github/GermanUSCO/Trabajos_data_science/blob/main/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [1]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

print(num_array)


[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [2]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

sliced_elements = num_array[3:]

print(sliced_elements)


[5 1 2]


Using slicing print all the elements except the last one.



In [3]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

elements_except_last = num_array[:-1]

print(elements_except_last)


[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [4]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

sliced_elements = num_array[1:5]

print(sliced_elements)


[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [5]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

reshaped_array = num_array.reshape(3, 2)

print("Original reshaped array:")
print(reshaped_array)

reshaped_again = reshaped_array.reshape(3, 2)

print("Reshaped again into 3x2:")
print(reshaped_again)


Original reshaped array:
[[7 8]
 [4 5]
 [1 2]]
Reshaped again into 3x2:
[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [6]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

for element in num_array:
    print(element)


7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [7]:
import numpy as np

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

print(new_num_array)


[0 6 9]


Join the two arrays.



In [8]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

concatenated_array = np.concatenate((num_array, new_num_array))

print(concatenated_array)


[7 8 4 5 1 2 0 6 9]


Using filtering print only the odd numbers of the joined array.



In [9]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

concatenated_array = np.concatenate((num_array, new_num_array))

odd_numbers = concatenated_array[concatenated_array % 2 != 0]

print(odd_numbers)


[7 5 1 9]


Sort the joined array elements.



In [10]:
import numpy as np

numbers = [7, 8, 4, 5, 1, 2]
num_array = np.array(numbers)

new_numbers = [0, 6, 9]
new_num_array = np.array(new_numbers)

concatenated_array = np.concatenate((num_array, new_num_array))

sorted_array = np.sort(concatenated_array)

print(sorted_array)


[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [12]:
import numpy as np

months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septimbre', 'Octubre', 'Noviembre', 'Diciembre']
months_array = np.array(months)

print(months_array)


['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septimbre' 'Octubre' 'Noviembre' 'Diciembre']


Split the months array in 4 periods of 3 elements each one.



In [13]:
import numpy as np

months = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre']
months_array = np.array(months)

split_periods = np.array_split(months_array, 4)

for period in split_periods:
    print(period)
    print("----")


['Enero' 'Febrero' 'Marzo']
----
['Abril' 'Mayo' 'Junio']
----
['Julio' 'Agosto' 'Septiembre']
----
['Octubre' 'Noviembre' 'Diciembre']
----


Create an array with genre information ['F','M','F','F','M','F'].



In [14]:
import numpy as np

gender_info = ['F', 'M', 'F', 'F', 'M', 'F']
gender_array = np.array(gender_info)

print(gender_array)


['F' 'M' 'F' 'F' 'M' 'F']


Find the indexes where the value is F.



In [15]:
import numpy as np

gender_info = ['F', 'M', 'F', 'F', 'M', 'F']
gender_array = np.array(gender_info)

indexes = np.where(gender_array == 'F')[0]

print("Indexes where value is 'F':", indexes)


Indexes where value is 'F': [0 2 3 5]


Store in an array the age information [18,20,19,23,19,20].



In [16]:
import numpy as np

age_info = [18, 20, 19, 23, 19, 20]
age_array = np.array(age_info)

print(age_array)


[18 20 19 23 19 20]


Create a filter array with values < 20.



In [17]:
import numpy as np

age_info = [18, 20, 19, 23, 19, 20]
age_array = np.array(age_info)

filter_array = age_array < 20

print(filter_array)


[ True False  True False  True False]


Change the 3 index element with a value of 22



In [18]:
import numpy as np

age_info = [18, 20, 19, 23, 19, 20]
age_array = np.array(age_info)

age_array[3] = 22

print(age_array)


[18 20 19 22 19 20]


Print the 4 index element.

In [19]:
import numpy as np

age_info = [18, 20, 19, 23, 19, 20]
age_array = np.array(age_info)

element_at_index_4 = age_array[4]

print(element_at_index_4)

19
